name: evaluate
run-name: evaluating model for ${{ github.actor }}
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  # cwd: /home/runner/work/ahri/ahri
      - uses: r-lib/actions/setup-r@v2

      # Download dataset
      - run: sudo apt-get install unzip
      - run: pip install kaggle
      - run: mkdir $HOME/.kaggle
      - env:
          KAGGLE_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        run: echo $KAGGLE_TOKEN > $HOME/.kaggle/kaggle.json
      - run: kaggle datasets download -d advaypatil/youtube-statistics

      # Unpack data
      - run: mkdir -p assets/data/
      - run: unzip youtube-statistics.zip -d assets/data/
      # - run: cat assets/data/comments.csv | head
      - name: Install packages
        run: |
          R -e 'install.packages("tokenizers")'
          R -e 'install.packages("dplyr")'
      
      # Run ingestion (should be done in a separate job)
      - run: Rscript ahri/ingest.r
